[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "reval-serial-transport"
version = "0.1.0"
description = "Serial data transport instrumentation MAVLINK Python applications."
readme = "README.md"
authors = [
    { name = "Felipe Nunes de Almeida Pereira" }
]
license = { text = "MIT" }
requires-python = ">=3.10"

dependencies = [
    "pymavlink",
    "pyserial"
]

[project.urls]
Homepage = "https://github.com/fnalmeidap/reval"
Documentation = "https://github.com/fnalmeidap/reval"
Source = "https://github.com/fnalmeidap/reval"

[tool.setuptools]
package-dir = { "" = "reval" }

[tool.setuptools.packages.find]
where = ["reval"]
